# Config file for automatic testing at travis-ci.org

sudo: required

language: python

python:
  - "3.5"

# configure a headless display to test plot generation
dist: xenial

services:
  - xvfb

before_install:
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

script:
  - python setup.py test

branches:
  - master
  - devel
