
version: '3.3'

services:
  snowav:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'snowav'
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '8888:3306'
    expose:
      - '3306'
    volumes:
      - /database/docker_snowav:/var/lib/mysql
      - /home/database/backup/snowav_database:/backup
      - /home/database/scripts/bgbackup_snowav.cnf:/home/bgbackup/bgbackup.cnf

volumes:
  db:
